#' rmodvege: R implementation of the grass growth model ModVege.
#'
#' @import R6
#' @import utils
#' @importFrom Rdpack reprompt
#'
#' @keywords internal
"_PACKAGE"

globalVariables(c("yield_parameters",
                  "management_parameters"))

#' Default options introduced by package rmodvege
#'
#' @description These are the default options, set when the package is loaded 
#'   by `library(rmodvege)`. To get or change the current value of an option, 
#' use the `options()` function.
#'
#' \describe{
#'   \item{rmodvege.verbosity}{Integer that controls how much console output is 
#'         generated by rmodvege functions. Higher numbers mean more output. 
#'         See [logger()].}
#'   \item{rmodvege.input_dir}{Name of the directory in which to look for 
#'         input files.}
#'   \item{rmodvege.output_dir}{Name of the directory into which output files
#'         are written.}
#'   \item{rmodvegedata_dir}{Name of the directory in which to look for 
#'         measured data files.}
#' }
#'
#' @seealso [options()]
#'
#' @export
rmodvege_package_options = list(
  rmodvege.verbosity = 3,
  rmodvege.input_dir = "input/",
  rmodvege.output_dir = "output/",
  rmodvege.data_dir = "data/"
  )

# This is run when the package is loaded
.onAttach = function(...) {
  rmodvege_version = packageVersion("rmodvege")
  message = sprintf("| Welcome to RModVege Version %s! |", rmodvege_version)
  line = paste0("+", paste(rep("-", nchar(message) - 2), collapse = ""), "+")
  packageStartupMessage(paste0(line, "\n", message, "\n", line, "\n"))
  # Set package options
  options(rmodvege_package_options)
}
